name: Testing jest

on:
  push:
    branches:
      - master

jobs:
  simple_testing_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup_node@v1
        with:
          node-version: '15.x'
      - name: npm install
        run: npm install 
      - name: npm test 
        run: npm test
      
